---
- name: Create folder for {{ installer_program_name }}
  become: true
  ansible.builtin.file:
    state: directory
    owner: root
    group: root
    mode: '0755'
    dest: "{{ installer_program_dir }}"

- name: Find {{ installer_program_name }}
  become: true
  ansible.builtin.find:
    paths:
      - /tmp
      - "{{ installer_download_path | default('/tmp') }}"
    patterns: "{{ installer_program_name }}$"
    use_regex: true
    get_checksum: true
    recurse: true
  register: _download

- name: Extract {{ installer_program_name }}
  become: true
  when: installer_program['checksum'] is not defined or installer_program['checksum'] != program_file['checksum']
  ansible.builtin.copy:
    remote_src: true
    src: "{{ program_file['path'] }}"
    dest: "{{ installer_program_dir }}"
    mode: preserve
  loop: "{{ _download['files'] | unique }}"
  loop_control:
    loop_var: program_file
    label: "{{ program_file['path'] | basename }}"

- name: Symlink {{ installer_program_name }}
  become: true
  ansible.builtin.file:
    src: "{{ installer_program_dir }}/{{ installer_program_name }}"
    path: /usr/local/bin/{{ installer_program_name }}
    mode: '0755'
    owner: root
    group: root
    state: hard
    force: true
