---
- name: Disable systemd service
  ansible.builtin.include_tasks: commands/stop.yml

- name: Uninstall metrics
  ansible.builtin.include_role:
    name: depin.core.metrics

- name: Uninstall dependencies
  vars:
    depin_cmd: uninstall
    ipfs_cluster_type: "{{ storagechain_ipfs_cluster_type }}"
  ansible.builtin.include_role:
    name: "{{ _role }}"
  loop:
    - depin.libs.ipfs_cluster
    - depin.libs.ipfs
  loop_control:
    loop_var: _role

- name: Uninstall
  become: true
  ansible.builtin.file:
    path: "{{ _remove }}"
    state: absent
    force: true
  loop:
    - /usr/local/bin/file-server-lin
    - /etc/systemd/system/file-server-lin.service
    - /opt/{{ role_name }}/
  loop_control:
    loop_var: _remove

- name: Assert
  when: "'molecule' in groups"
  block:
    - name: Common uninstall asserts
      ansible.builtin.include_tasks:
        file: tasks/asserts_uninstall.yml
