---
- name: Deploy VM on LXD
  connection: local
  become: true
  block:
    - name: Update default profile
      community.general.lxd_profile:
        merge_profile: true
        name: default
        config:
          user.location: "{{ lxd_hostname }}"
        state: present

    - name: Create VM profile
      when: lxd_vm_public_ipv4_address | length > 0
      community.general.lxd_profile:
        name: "{{ _short_vm_hostname }}"
        config:
          user.location: "{{ lxd_hostname }}"
          cloud-init.network-config: |
            network:
              version: 2
              ethernets:
                enp5s0:
                  routes:
                  - to: default
                    via: 169.254.0.1
                    on-link: true
                  addresses:
                  - "{{ lxd_vm_public_address }}/32"
                  nameservers:
                    addresses:
                    - 8.8.8.8
                    - 1.1.1.1
                    search: []
        description: Routed LXD profile
        devices:
          eth0:
            ipv4.address: "{{ lxd_vm_public_address }}"
            nictype: routed
            parent: "{{ ansible_default_ipv4.interface }}"
            type: nic
          root:
            path: /
            pool: default
            type: disk
        state: present
      register: routed_profile

    - name: Recreate VM
      when: lxd_vm_recreate
      delegate_to: localhost
      community.general.lxd_container:
        name: "{{ _short_vm_hostname }}"
        state: absent

    - name: Create VM
      delegate_to: localhost
      community.general.lxd_container:
        name: "{{ _short_vm_hostname }}"
        ignore_volatile_options: true
        type: virtual-machine
        state: started
        source:
          protocol: simplestreams
          type: image
          mode: pull
          alias: "{{ lxd_vm_image }}"
          server: https://cloud-images.ubuntu.com/releases
        config:
          limits.cpu: "{{ lxd_vm_vcpus }}"
          limits.memory: "{{ lxd_vm_memory }}"
          cloud-init.user-data: "{{ lookup('ansible.builtin.template', 'templates/user-data.yml.j2') }}"
        devices:
          root:
            path: /
            pool: default
            type: disk
            size: "{{ lxd_vm_disk }}"
        profiles:
          - "{{ (routed_profile is changed) | ternary(_short_vm_hostname, 'default') }}"
        wait_for_ipv4_addresses: true
        wait_for_container: true
        timeout: 300
      register: deploy_vm

    - name: Re-run cloud-init on instance
      when:
        - deploy_vm is defined
        - not deploy_vm is changed 
      vars:
        ansible_connection: lxd
        ansible_lxd_host: "{{ _short_vm_hostname }}"
      ansible.builtin.command: cloud-init clean --logs --reboot
      changed_when: false
