---
- name: Install docker
  ansible.builtin.include_role:
    name: depin.libs.docker

- name: Start node
  ansible.builtin.include_tasks:
    file: commands/start.yml

## should we backup keys
# https://docs.presearch.io/nodes/troubleshooting-and-maintenance/backup-method-for-linux
