---
metrics_cmd: "{{ depin_cmd | default('install') }}"
metrics_parent_role_name: "{{ ansible_parent_role_names | last | split('.') | last | basename }}"

## starting with 33001
metrics_port:
  presearch: 33001
  autonomi: 33002
  hychain: 33003
  storagechain: 33004
