---
- name: "ethereum_besu {{ ethereum_besu_cmd }}"
  ansible.builtin.include_tasks:
    file: "commands/{{ ethereum_besu_cmd }}.yml"

#- name: Ensure metrics is installed
#  ansible.builtin.include_tasks:
#    file: metrics.yml