---
storagechain_cmd: "{{ depin_cmd | default('install') }}"
storagechain_credentials: "{{ service_credentials }}"

storagechain_ipfs_cluster_type: service
storagechain_programs:
  - ipfs
  - ipfs-cluster-{{ storagechain_ipfs_cluster_type }}
  - file-server-lin

storagechain_download_urls:
  - https://file-view-prod.storagechain.io/api/file/download/QRFhcWOyVN9IqxdOYmhQh2K84iqhMo9O
# storagechain_ipfs_checksum: 47af81af0c1c0aeb26e879cf3b5e548ae9a9ff56
# storagechain_ipfs_cluster_checksum: 144ae74c02d86be5c13c38c6da4358f4769de842
storagechain_ipfs_cluster_remote_config: http://94.72.127.176:8080/ipns/k51qzi5uqu5dlb5l2sctf6csb72qmcs70u0y454vmsgu6w38jd9fdqb7155wjg

storagechain_version: v3.1.5
storagechain_dir: /opt/storagechain/{{ storagechain_version }}

storagechain_cluster_secret: a89fe67688f00ee7cb5eb25084f9971174433cd15a6349783a2c268b8bed730a
storagechain_cluster_bootstrap: /ip4/94.72.127.176/tcp/9096/p2p/12D3KooWFzRLHNCx88WhrCkNGGb1SNRj8TCajzErfa4nJtfniA2B

storagechain_node_name: "{{ lookup('env', 'STORAGECHAIN_CUSTOM_NAME') | default(storagechain_credentials['custom_fields']['custom_name']) }}"
storagechain_node_id: "{{ lookup('env', 'STORAGECHAIN_NODE_ID') | default(storagechain_credentials['custom_fields']['nodeid']) }}"
storagechain_default_dns: "{{ storagechain_node_id }}.sc.nerdnode.io"
storagechain_dns: "{{ lookup('env', 'STORAGECHAIN_DNS') | default(storagechain_credentials['custom_fields']['dns']) | default(storagechain_default_dns) }}"
storagechain_email: "{{ lookup('env', 'STORAGECHAIN_USERNAME') | default(storagechain_credentials['custom_fields']['username']) }}"
storagechain_password: "{{ lookup('env', 'STORAGECHAIN_PASSWORD') | default(storagechain_credentials['plaintext']) }}"
storagechain_ipfs_cluster_args: "{{ storagechain_email }}:{{ storagechain_password }}:{{ storagechain_node_id }}"

storagechain_node_size: "2000GB"

storagechain_firewall:
  protocol:
    value: tcp
  ports:
    - 3008
    - 4001
    - 5001
    - 8080
    - 9094
    - 9095
    - 9096
